// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg0QyBGk29UypERqjBN3wGFFqdRz2DxfQ',
    appId: '1:427823845632:web:e1b39ce961be65f8c363e5',
    messagingSenderId: '427823845632',
    projectId: 'quote-builder-35375',
    authDomain: 'quote-builder-35375.firebaseapp.com',
    storageBucket: 'quote-builder-35375.firebasestorage.app',
    measurementId: 'G-KSFQGCLETZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rsZVi31XRuST5rCQ0vqtFsPSZ7Fnafw',
    appId: '1:427823845632:android:298ef4d6590da453c363e5',
    messagingSenderId: '427823845632',
    projectId: 'quote-builder-35375',
    storageBucket: 'quote-builder-35375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAqRBHMeVbTFw74-5ndnE18H2J4th54Ic',
    appId: '1:427823845632:ios:3ff4d85f46d55169c363e5',
    messagingSenderId: '427823845632',
    projectId: 'quote-builder-35375',
    storageBucket: 'quote-builder-35375.firebasestorage.app',
    iosBundleId: 'com.example.dailyQuoates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAqRBHMeVbTFw74-5ndnE18H2J4th54Ic',
    appId: '1:427823845632:ios:3ff4d85f46d55169c363e5',
    messagingSenderId: '427823845632',
    projectId: 'quote-builder-35375',
    storageBucket: 'quote-builder-35375.firebasestorage.app',
    iosBundleId: 'com.example.dailyQuoates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg0QyBGk29UypERqjBN3wGFFqdRz2DxfQ',
    appId: '1:427823845632:web:d68bd88827db49efc363e5',
    messagingSenderId: '427823845632',
    projectId: 'quote-builder-35375',
    authDomain: 'quote-builder-35375.firebaseapp.com',
    storageBucket: 'quote-builder-35375.firebasestorage.app',
    measurementId: 'G-EK2HQD829P',
  );
}
